FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /DockQueue
COPY . .
RUN dotnet restore DockQueue.API/DockQueue.API.csproj
RUN dotnet publish DockQueue.API/DockQueue.API.csproj -c Release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app ./
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
ENTRYPOINT ["dotnet","DockQueue.API.dll"]
